version: "3"

services:

  sut:
    build:
      context: ./
      dockerfile: Dockerfile.test
    command: ./run-rest-test.sh
    depends_on:
      - rest

  rest:
    build: .
    ports:
      -  "8080:8080"