version: '2'

services:

  sut:
    build: ./rest-service-api-test/
    depends on:
      - rest
    networks:
      - back-end

  rest:
    build: ./hello-world-rest-service/
    networks:
      - back-end

  networks:
    back-end:
