FROM java:8-jdk-alpine
LABEL maintainer="selitektay@gmail.com"
VOLUME /tmp
RUN mkdir docker-demo
COPY . /docker-demo/
RUN apk update && apk add bash
WORKDIR /docker-demo/
RUN chmod +x  run-rest-test.sh
RUN ./gradlew build -x test
